config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  root to: 'pages#home'
  resources :buildings
  resources :flats, only: [:index]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/building.rb
class Building < ApplicationRecord

  validates :address, :lat, :lng, presence: true
  geocoded_by :address
  # after_validation :geocode, if: :will_save_change_to_address?

  def diagonal
  distance([ne_lat, ne_lng],[sw_lat, sw_lng])
  end

  def surface
    (diagonal * diagonal) / 2
  end

  private

  def distance(loc1, loc2)
    rad_per_deg = Math::PI / 180  # PI / 180
    rkm = 6371                  # Earth radius in kilometers
    rm = rkm * 1000             # Radius in meters

    dlat_rad = (loc2[0]- loc1[0]) * rad_per_deg  # Delta, converted to rad

    dlon_rad = (loc2[1] - loc1[1]) * rad_per_deg

    lat1_rad, lon1_rad = loc1.map { |i| i * rad_per_deg }
    lat2_rad, lon2_rad = loc2.map { |i| i * rad_per_deg }

    a = Math.sin(dlat_rad/2)**2 + Math.cos(lat1_rad) * Math.cos(lat2_rad) * Math.sin(dlon_rad/2)**2
    c = 2 * Math::atan2(Math::sqrt(a), Math::sqrt(1 - a))

    rm * c # Delta in meters

  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
# before_action :authenticate_user!
end

app/controllers/buildings_controller.rb
require "uri"
require "net/http"
require "json"
require 'googlestaticmap'

class BuildingsController < ApplicationController
  before_action :set_building, only: %i[show edit update destroy]

  def index
    @buildings = Building.all
  end

  def show
    @markers = {
      lat: @building.lat,
      lng: @building.lng
    }
  end

  def new
    @building = Building.new
  end

  def create
    @building = Building.new(set_params)
    client = OpenStreetMap::Client.new
    result = client.search(q: @building.address, format: 'json', addressdetails: '1', accept_language: 'fr')
    unless result.count.zero?
      @building.address = result[0]["display_name"]
      @building.lat = result[0]["lat"]
      @building.lng = result[0]["lon"]
      @building.ne_lat = result[0]["boundingbox"][0]  #min Longitude
      @building.ne_lng = result[0]["boundingbox"][2]  #min Latitude
      @building.sw_lat = result[0]["boundingbox"][1] #max Longitude
      @building.sw_lng = result[0]["boundingbox"][3] #max Latitude
    end
    if @building.save
      redirect_to building_path(@building)
    else
      redirect_to new_building_path
      flash.alert = "Address invalid"
    end
  end

  def edit
  end

  def update
    @building.update(set_params)
  end

  def destroy
    @building.delete
  end

  private

  def set_params
    params.require(:building).permit(:address, :lat, :lng, :ne_lng, :ne_lat, :sw_lat, :sw_lng, :surface, :nom)
  end

  def set_building
    @building = Building.find(params[:id])
  end

  def google_place_api
    @google_api = ENV['GOOGLE_PLACE_API']
  end

  def search_request(string)
    ascii_string = ActiveSupport::Inflector.transliterate(string)
    url = URI("https://maps.googleapis.com/maps/api/place/findplacefromtext/json?input=#{ascii_string}&inputtype=textquery&fields=formatted_address%2Cname%2Crating%2Copening_hours%2Cgeometry&key=#{google_place_api}")

    https = Net::HTTP.new(url.host, url.port)
    https.use_ssl = true

    request = Net::HTTP::Get.new(url)

    response = https.request(request)
    response.read_body
    JSON.parse(response.read_body, object_class: Hash)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # skip_before_action :authenticate_user!, only: [:home]
  def home
    @building = Building.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/buildings/_form.html.erb
<div class="container">
<%= simple_form_for @building do |f| %>
  <%= f.input :address, placeholder: "Rte de Balata, Fort-de-France 97200, Martinique" %>
  <%= f.submit %>
<% end %>

</div>

app/views/buildings/_map.html.erb
<div style="width: 100%; height: 600px;"
    data-controller="mapbox"
    data-mapbox-markers-value="<%= @markers.to_json %>"
    data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>

app/views/buildings/edit.html.erb
<%= render 'form' %>>

app/views/buildings/index.html.erb
<div class="container-list pt-2">
<% @buildings.each do |building| %>
  <%= link_to  building_path(building), class: "link" do %>

    <ul class="ul-list bg-white">
      <li class="li-element" >
        <span class="infos-location"> Address :</span> <%= building.address %>
      </li>
      <li class="li-element" >
        <span class="infos-location"> Lat : </span> <%= building.lat %>
      </li>
      <li class="li-element" >
        <span class="infos-location"> Longitude : </span> <%= building.lng %>
      </li>
    </ul>
  <% end %>
<% end %>
</div>

app/views/buildings/new.html.erb
<%= render 'form' %>

app/views/buildings/show.html.erb
<div class="container">
<div class="row">
  <div class="card-trip">
      <img src="https://media.istockphoto.com/photos/modern-full-black-solar-panels-on-the-roof-of-a-house-picture-id1368767863?b=1&k=20&m=1368767863&s=170667a&w=0&h=8ZbPuelGJJcpaBz5M6INTx_BERdZoje7MskPw7jKfeY= "/>
    <div class="card-trip-infos">
      <div>
        <h2>ROOF CALCULATOR</h2>
        <p class= "pa-address">
        <span class="infos-address"><a class="btn btn-gradient" href="#">Address</a></span> <%= @building.address %></p>
        <p class= "pa-diagonale">
        <span class="infos-diagonal"><a class="btn btn-gradient" href="#">Diagonal</a></span> <%= @building.diagonal.round %> m </p>
        <p class= "pa-surface">
        <span class="infos-surface"><a class="btn btn-gradient" href="#">Surface</a></span> <%= @building.surface.round%> m2 </p>
      </div>
    </div>
  </div>
  <%= render 'map'%>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RoofCalculateor</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container ">
  <div class="row">
    <div class="col-12  p-5">

    <h1 class="text-center">WELCOME TO ROOFING CALCULATOR APP </h1>
    </div>
    <div class="col p-5">
    <h2  class=" w-50 fs-2">EASILY FIND THE GEOMETRY OF YOUR ROOF WITH <span class="text-primary font-weight-bold roofing-weight">ROOFING CALCULATOR</span></h2>
    <p class="fs-3">Our product was designed to be intuitive and easy to use.
    It will help you get the closest possible roof surface, avoid wasting money and save time.
    </p>
    <%= link_to buildings_path, class: "rounded bg-primary text-white p-1 btn " do  %>
    View Ours Buildings
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-building" viewBox="0 0 16 16">
  <path fill-rule="evenodd" d="M14.763.075A.5.5 0 0 1 15 .5v15a.5.5 0 0 1-.5.5h-3a.5.5 0 0 1-.5-.5V14h-1v1.5a.5.5 0 0 1-.5.5h-9a.5.5 0 0 1-.5-.5V10a.5.5 0 0 1 .342-.474L6 7.64V4.5a.5.5 0 0 1 .276-.447l8-4a.5.5 0 0 1 .487.022zM6 8.694 1 10.36V15h5V8.694zM7 15h2v-1.5a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 .5.5V15h2V1.309l-7 3.5V15z"/>
  <path d="M2 11h1v1H2v-1zm2 0h1v1H4v-1zm-2 2h1v1H2v-1zm2 0h1v1H4v-1zm4-4h1v1H8V9zm2 0h1v1h-1V9zm-2 2h1v1H8v-1zm2 0h1v1h-1v-1zm2-2h1v1h-1V9zm0 2h1v1h-1v-1zM8 7h1v1H8V7zm2 0h1v1h-1V7zm2 0h1v1h-1V7zM8 5h1v1H8V5zm2 0h1v1h-1V5zm2 0h1v1h-1V5zm0-2h1v1h-1V3z"/>
</svg>
    <% end %>
    <%= link_to  new_building_url, class: "rounded bg-white text-black p-1 btn" do %>
    Search A Building
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-binoculars" viewBox="0 0 16 16">
    <path d="M3 2.5A1.5 1.5 0 0 1 4.5 1h1A1.5 1.5 0 0 1 7 2.5V5h2V2.5A1.5 1.5 0 0 1 10.5 1h1A1.5 1.5 0 0 1 13 2.5v2.382a.5.5 0 0 0 .276.447l.895.447A1.5 1.5 0 0 1 15 7.118V14.5a1.5 1.5 0 0 1-1.5 1.5h-3A1.5 1.5 0 0 1 9 14.5v-3a.5.5 0 0 1 .146-.354l.854-.853V9.5a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5v.793l.854.853A.5.5 0 0 1 7 11.5v3A1.5 1.5 0 0 1 5.5 16h-3A1.5 1.5 0 0 1 1 14.5V7.118a1.5 1.5 0 0 1 .83-1.342l.894-.447A.5.5 0 0 0 3 4.882V2.5zM4.5 2a.5.5 0 0 0-.5.5V3h2v-.5a.5.5 0 0 0-.5-.5h-1zM6 4H4v.882a1.5 1.5 0 0 1-.83 1.342l-.894.447A.5.5 0 0 0 2 7.118V13h4v-1.293l-.854-.853A.5.5 0 0 1 5 10.5v-1A1.5 1.5 0 0 1 6.5 8h3A1.5 1.5 0 0 1 11 9.5v1a.5.5 0 0 1-.146.354l-.854.853V13h4V7.118a.5.5 0 0 0-.276-.447l-.895-.447A1.5 1.5 0 0 1 12 4.882V4h-2v1.5a.5.5 0 0 1-.5.5h-3a.5.5 0 0 1-.5-.5V4zm4-1h2v-.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5V3zm4 11h-4v.5a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5V14zm-8 0H2v.5a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5V14z"/>
    </svg>
    <% end %>

    </div>
    <div class="col bg-info ">
      <h3 class="text-center pt-1">Don't know how to start ? </h3>
    <ol class="pt-3" >
      <li class="ordered-list">
      Go to the link
      <%= link_to  "new", new_building_path,  class: "text-black" %>
      </li>
      <li class="ordered-list">
      Type your Address in the search bar
      </li>
          <span class="fs-5">ex : <code class="text-muted fs-4">Palais des congrès de Madiana, Schoelcher 97232, Martinique</code> </span>
      <li class="ordered-list">
      Click on Create Building
      </li>
    </ol>
    <p class="text-center h2">And that's it, you should be redirected</p>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "/", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <li class="nav-item active">
          </li>
            <%= link_to "new", new_building_path, class: "nav-link" %>
          <li class="nav-item">
            <%= link_to "Buildings", buildings_path, class: "nav-link" %>
          </li>
      </ul>
    </div>
  </div>
</div>